version: '3.8'

services:
  telegram_bot:
    build: telegrambot
    image: telegrambot:0.0.0
    ports:
      - '443:443'
    environment:
      - IP_ADDRESS=${IP_ADDRESS}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
    volumes:
      - ./telegrambot/output:/app/output
