version: '3.8'

services:
  telegram_bot:
    build: telegram-bot-simple
    image:  sfarhad/telegram-bot-simple:0.0.1
    ports:
      - '443:443'
    environment:
      - IP_ADDRESS=${IP_ADDRESS}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
    volumes:
      - ./telegram-bot-simple/output:/app/output
