name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Add SSH private key to SSH agent
        run: ssh-agent bash -c "echo '${{ secrets.SSH_PRIVATE_KEY }}' | ssh-add -k"

    - name: Deploy to Google Cloud
      env:
        SSH_CONFIG: ${{ github.workspace }}/ssh_config
        SSH_KNOWN_HOSTS: ~/.ssh/known_hosts
      run: |
        ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> $SSH_KNOWN_HOSTS
        ssh -vvv -o UserKnownHostsFile=$SSH_KNOWN_HOSTS -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd ~/telegrambot && docker compose down && docker system prune -af && git pull && docker-compose up -d"
