name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
        chmod 600 ssh_key
        echo "Host ${{ secrets.SSH_HOST }}\n  IdentityFile $(pwd)/ssh_key\n  UserKnownHostsFile=/dev/null" > ssh_config

    - name: Deploy to Google Cloud
      env:
        SSH_CONFIG: ${{ github.workspace }}/ssh_config
        SSH_KNOWN_HOSTS: ${{ github.workspace }}/known_hosts
      run: |
        ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> $SSH_KNOWN_HOSTS
        ssh -o UserKnownHostsFile=$SSH_KNOWN_HOSTS -F $SSH_CONFIG ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd ~/telegrambot && docker compose down && docker prune -af && git pull && docker-compose up -d"
