name: Deploy to Google Cloud

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Dockerhub Publish"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/id_rsa
        chmod 600 ~/id_rsa
    - name: Deploy to Google Cloud
      env:
        BRANCH: main
        CONTAINER_DIR: telegrambot 
        CONTAINER_NAME: telegram-bot-simple
        TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}}
        IP_ADDRESS: ${{secrets.SSH_HOST}}
        SSL_PORT: ${{secrets.SSL_PORT}}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: |
        ssh-keyscan -t rsa $IP_ADDRESS >> ~/known_hosts
        ssh -o UserKnownHostsFile=~/known_hosts \
            -i ~/id_rsa $SSH_USERNAME@$IP_ADDRESS \
                "export BRANCH=${{env.BRANCH}} \
                && export CONTAINER_DIR=${{env.CONTAINER_DIR}} \
                && export CONTAINER_NAME=${{env.CONTAINER_NAME}} \
                && export SSL_PORT=${{env.SSL_PORT}} \
                && export TG_BOT_TOKEN=${{env.TG_BOT_TOKEN}} \
                && export IP_ADDRESS=${{env.IP_ADDRESS}} \
                && cd $CONTAINER_DIR \
                && git fetch --all \
                && git switch $BRANCH \
                && git merge origin/$BRANCH \
                && docker compose down \
                && docker system prune -af \
                && docker compose up -d \
                && docker ps -q --filter name=^${CONTAINER_NAME}1$ | grep -q . \
                  || echo Docker container is not running"
