name: Build and Push Docker Image to Google Cloud Platform

on:
  push:
    branches: [ main ]

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID_GCP }}
          export_default_credentials: true
      
      - name: Build Docker Image
        run: docker build -t gcr.io/${{ secrets.PROJECT_ID_GCP }}/${{ env.IMAGE_NAME }}:latest $IMAGE_NAME
        env:
          IMAGE_NAME: telegram-bot-simple
      
      - name: Configure Docker Client
        run: gcloud auth configure-docker --quiet

      - name: Push Docker Image to Container Registry (GCR)
        run: docker push gcr.io/${{ secrets.PROJECT_ID_GCP }}/${{ env.IMAGE_NAME }}:latest
        env:
          IMAGE_NAME: telegram-bot-simple

